In [1]:
# -*- coding: utf-8 -*-
import os
import pickle
from typing import List

import pandas
import numpy as np
from tqdm import tqdm

In [2]:
orig_name = 'Dataset II-4.csv'
csv_name = 'II-4'

In [3]:
'''
è¯» csv
'''
assert os.path.exists('../../data')
dataset = pandas.read_csv('../../data/Dataset II (mismatch-only)/%s' % orig_name, delimiter=',')
dataset

/tmp/ipykernel_3480760/2716458706.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pandas.read_csv('../../data/Dataset II (mismatch-only)/%s' % orig_name, delimiter=',')

,Unnamed: 0,Targetsite,Num mismatches,GUIDE-SEQ Reads,30mer,30mer_mut,chromosome,start,end,gene,strand,Category,Annotation,20mer
0,0,VEGFA_site1,2,0.386461,GGGTGGGGGGAGTTTGCTCCTGG,GGATGGAGGGAGTTTGCTCCTGG,15,65345193,65345217,IGDCC3,-,SomeTypeMutation,"['A:G,3', 'A:G,7']",GGGTGGGGGGAGTTTGCTCC
1,1,VEGFA_site3,2,0.173872,GGTGAGTGAGTGTGTGCGTGGGG,AGTGAGTGAGTGTGTGTGTGGGG,14,65102435,65102459,MAX,-,SomeTypeMutation,"['A:G,1', 'T:C,17']",GGTGAGTGAGTGTGTGCGTG
2,2,EMX1,2,0.485692,GAGTCCGAGCAGAAGAAGAAAGG,GAGTTAGAGCAGAAGAAGAAAGG,5,45358959,45358983,HCN1,-,SomeTypeMutation,"['T:C,5', 'A:C,6']",GAGTCCGAGCAGAAGAAGAA
3,3,VEGFA_site3,3,0.142380,GGTGAGTGAGTGTGTGCGTGAGG,AGAGAGTGAGTGTGTGCATGAGG,5,90145146,90145170,NoGene,-,SomeTypeMutation,"['A:G,1', 'A:T,3', 'A:G,18']",GGTGAGTGAGTGTGTGCGTG
4,4,HEK293_sgRNA4,3,0.109805,GGCACTGCGGCTGGAGGTGGTGG,TGCACTGCGGCCGGAGGAGGTGG,20,61435490,61435514,CDH4,+,SomeTypeMutation,"['T:G,1', 'C:T,12', 'A:T,18']",GGCACTGCGGCTGGAGGTGG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294529,294529,NaN,6,0.000000,GGTGAGTGAGTGTGTGCGTGAGG,GAAGTGTCAGTGTGTGTGTAAGG,Y,23767786,23767810,NoGene,+,SomeTypeMutation,"['A:G,2', 'A:T,3', 'T:A,5', 'C:G,8', 'T:C,17',...",GGTGAGTGAGTGTGTGCGTG
294530,294530,NaN,6,0.000000,GGTGAGTGAGTGTGTGCGTGGGG,CGTGGGAGGGTGTATGTGTGGAG,Y,23963748,23963772,NoGene,-,SomeTypeMutation,"['AG', 'C:G,1', 'G:A,5', 'A:T,7', 'G:A,9', 'A:...",GGTGAGTGAGTGTGTGCGTG
294531,294531,NaN,6,0.000000,GGTGAGTGAGTGTGTGCGTGAGG,GGTGAGTGGGGGTGTGGACCAGG,Y,24186470,24186494,NoGene,-,SomeTypeMutation,"['G:A,9', 'G:T,11', 'G:C,17', 'A:G,18', 'C:T,1...",GGTGAGTGAGTGTGTGCGTG
294532,294532,NaN,6,0.000000,GGTGAGTGAGTGTGTGCGTGCGG,CATGTCTGTGTGTGTGTGTGCAG,Y,24262094,24262118,NoGene,+,SomeTypeMutation,"['AG', 'C:G,1', 'A:G,2', 'T:A,5', 'C:G,6', 'T:...",GGTGAGTGAGTGTGTGCGTG
294533,294533,NaN,6,0.000000,GGTGAGTGAGTGTGTGCGTGAGG,ACTACTTGAGTTTGTGCGTGAAG,Y,26595381,26595405,NoGene,-,SomeTypeMutation,"['AG', 'A:G,1', 'C:G,2', 'A:G,4', 'C:A,5', 'T:...",GGTGAGTGAGTGTGTGCGTG

In [4]:
on = dataset['30mer']
off = dataset['30mer_mut']
reads = dataset['GUIDE-SEQ Reads']
reads = np.array(reads)
val = np.zeros(len(reads))
val[reads > 0] = 1
on,off,val

(0         GGGTGGGGGGAGTTTGCTCCTGG
 1         GGTGAGTGAGTGTGTGCGTGGGG
 2         GAGTCCGAGCAGAAGAAGAAAGG
 3         GGTGAGTGAGTGTGTGCGTGAGG
 4         GGCACTGCGGCTGGAGGTGGTGG
                    ...
 294529    GGTGAGTGAGTGTGTGCGTGAGG
 294530    GGTGAGTGAGTGTGTGCGTGGGG
 294531    GGTGAGTGAGTGTGTGCGTGAGG
 294532    GGTGAGTGAGTGTGTGCGTGCGG
 294533    GGTGAGTGAGTGTGTGCGTGAGG
 Name: 30mer, Length: 294534, dtype: object,
 0         GGATGGAGGGAGTTTGCTCCTGG
 1         AGTGAGTGAGTGTGTGTGTGGGG
 2         GAGTTAGAGCAGAAGAAGAAAGG
 3         AGAGAGTGAGTGTGTGCATGAGG
 4         TGCACTGCGGCCGGAGGAGGTGG
                    ...
 294529    GAAGTGTCAGTGTGTGTGTAAGG
 294530    CGTGGGAGGGTGTATGTGTGGAG
 294531    GGTGAGTGGGGGTGTGGACCAGG
 294532    CATGTCTGTGTGTGTGTGTGCAG
 294533    ACTACTTGAGTTTGTGCGTGAAG
 Name: 30mer_mut, Length: 294534, dtype: object,
 array([1., 1., 1., ..., 0., 0., 0.]))

In [5]:
tlen =24
ons = []
offs = []
for i in range(len(on)):
    ons.append('-'*(tlen-len(on[i]))+on[i])
for i in range(len(off)):
    offs.append('-'*(tlen-len(off[i]))+off[i])

In [6]:
min([len(s) for s in ons])

24

In [7]:
onss = []
for i in tqdm(range(len(ons))):
    seq = []
    for j in range(tlen):
        if ons[i][j]=='N':
            seq.append(offs[i][j])
        else:
            seq.append(ons[i][j])
    onss.append(''.join(seq))
onss[0:10]

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 294534/294534 [00:01<00:00, 186725.65it/s]

['-GGGTGGGGGGAGTTTGCTCCTGG',
 '-GGTGAGTGAGTGTGTGCGTGGGG',
 '-GAGTCCGAGCAGAAGAAGAAAGG',
 '-GGTGAGTGAGTGTGTGCGTGAGG',
 '-GGCACTGCGGCTGGAGGTGGTGG',
 '-GGTGAGTGAGTGTGTGCGTGAGG',
 '-GGAATCCCTTCTGCAGCACCAGG',
 '-GGCACTGCGGCTGGAGGTGGTGG',
 '-GGTGAGTGAGTGTGTGCGTGTGG',
 '-GGGTGGGGGGAGTTTGCTCCTGG']

In [8]:
df = pandas.DataFrame(data={
    'on':onss,
    'off':offs,
    'val':val
})
df.to_csv('../../data/%s.csv' % csv_name, index=False)